name: build_and_push_image
on:
  push:
    branches:
      - 'master'
      - 'main'
jobs:
  build-2019:
    runs-on: windows-2019
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack
      -
        name: Choco install git
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install git -y
      -
        name: Choco install
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install trivy -y -s .
      - name: Trivy run
        run: |
          trivy version
        shell: powershell
  build-2022:
    runs-on: windows-2022
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack
      -
        name: Choco install git
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install git -y
      -
        name: Choco install
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install trivy -y -s .
      - name: Trivy run
        run: |
          trivy version
        shell: powershell
      -
        name: Choco push
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: push --source https://push.chocolatey.org/ -k=${{ secrets.CHOCO_API_KEY }} -v
